[package]
name = "RustAPI"
version = "0.1.0"
authors = ["Admin <faheemuzzaman@hotmail.com>"]
edition = "2018"


[dependencies]
aux5 = { path = "auxiliary" }

[[bin]]
name = "main"
path = "src/main.rs"
